name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      # - run: pnpm dlx nx start-nx-agents

      - uses: pnpm/action-setup@v4
        id: pnpm

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm exec nx run-many -t lint test build

      - run: pnpm exec nx fix-ci
        if: failure() && steps.pnpm.outcome == 'success'
